export default {
    "data": {
        baseInfo:{
            nikeName:'White',
            firstName:'张',
            lastName:'凌浩',
            nameFootNote:'追求专业与卓越前端开发者',
            gender:'男',
            age:'26',
            education:'专科',
            exp:'3年前端开发经验',
            phone:'17612235899',
            QQ:'271793819',
            email:'17612235899@163.com',
            gitHub:'https://github.com/linghaozhang',
            location:'天津'
        },
        introduce:{
            content:[
                "3年＋的前端开发经验。2年＋的北京React开发经验。做过些内部管理系统和电商。",
                "熟悉前端项目构建，有过基于 react 的项目架构工作经验。",
                "经常使用 antd 和 less，喜欢逛掘金，sf，github等开发者社区",
                "有做过web APP。"
            ],
            tech:['react','ES6','less','antd','antd-mobile','webpack','jquery','bootStrap','H5','git']
        },
        experience:[
            {
                time:"2016.3-2016.10",
                title:"易商互动",
                proTitle:"信美电商积分兑换系统",
                intro:"中级前端开发",
                description:"主要负责基于react的Pc和webApp的前端开发，系统支持内部积分兑换，支付宝购买等流程。",
                tips:[
                    {
                        title:"主要业绩：",
                        content:[
                            "自己重构了之前的积分兑换代码，组件化思想开发，是代码可读性大大提高。",
                            "实现了整个系统的兑换流程的优化。实现前后端分离。",
                            "给组内成员做了技术分享。"
                        ]
                    }
                ],
                technology:[
                    {
                        title:"技术栈：",
                        content:[
                            "react","antd","antd-mobile","webpack","less","ES6"
                        ]
                    }
                ]
            },
            {
                time:"2016.7-2017.10",
                title:"易商互动",
                proTitle:"信美保险产品",
                intro:"中级前端开发",
                description:"主要负责基于react的信美保险产品的开发,主要流程包括险种价格试算，投被保人信息，健康告知，face++人脸识别。",
                tips:[
                    {
                        title:"主要业绩：",
                        content:[
                            "期间做了：共创配置中心，海外医疗，高端医疗，交通意外，短期意外等险种",
                            "在前端架构leader的带领下，优化了配置中心的数据模型，使共创中心实现了多渠道对接。",
                            "同时在app端重构了家庭成员组件"
                        ]
                    }
                ],
                technology:[
                    {
                        title:"技术栈：",
                        content:[
                            "react","antd","antd-mobile","webpack","less","ES6"
                        ]
                    }
                ]
            },
            {
                time:"2017.7-2017.9",
                title:"易商互动",
                proTitle:"标准工程",
                intro:"中级前端开发",
                description:"主要负责工程内常用方法、组件的封装",
                tips:[
                    {
                        title:"主要业绩：",
                        content:[
                            "期间封装了基于fetch的异步请求方法",
                            "基于antd2.x的表单组件封装",
                            "参与了使用标准工程开发的外部bp系统，企业管理部分"
                        ]
                    }
                ],
                technology:[
                    {
                        title:"技术栈：",
                        content:[
                            "react","antd","antd-mobile","webpack","less","ES6"
                        ]
                    }
                ]
            },
            {
                time:"2016.7-2017.10",
                title:"易商互动",
                proTitle:"电商保全项目",
                intro:"中级前端开发",
                description:"该项目基于已承保的用户，进行保全申请操作",
                tips:[
                    {
                        title:"主要业绩：",
                        content:[
                            "完成了贷款清偿，减保保全项目",
                            "使用了face++人脸识别，对用户进行身份鉴定",
                            "参与了清偿需求分析，与后端共同制定报文"
                        ]
                    }
                ],
                technology:[
                    {
                        title:"技术栈：",
                        content:[
                            "react","antd","antd-mobile","webpack","less","ES6"
                        ]
                    }
                ]
            }
        ],
        skill:[
            {
                name:"HTML",
                percent:"90%"
            },
            {
                name:"Css",
                percent:"90%"
            },
            {
                name:"React",
                percent:"80%"
            },
            {
                name:"JavaScript",
                percent:"70%"
            },
            {
                name:"ES6",
                percent:"75%"
            },
            {
                name:"Antd",
                percent:"75%"
            },
            {
                name:"Git",
                percent:"70%"
            }
        ],
        usually:[
            {
                name:"GitHub",
                description:"收集代码并写下自己的理解"
            },
            {
                name:"掘金",
                description:"学习一些技术文章"
            },
            {
                name:"思否 SegmentFault",
                description:"收藏并学习新的技术"
            }
        ],
        resumeIntroduce:{
            content:[
                "本简历基于react+webpack+ES6制作，",
                "数据存放在esaymock，通过fetch请求获得。",
                "如果您想配置成自己的简历，或者想看如何实现，",
                "请点击屏幕右上角按钮访问我的github主页。"
            ]
        }
    }
}